### ISSUE TITLE
Invalid address length, expected 40 got 34 bytes

### ISSUE THREAD

**Issue by CodePrem** [mintme-com/old-wallet#228]
``` 
JsonRpcError: Invalid address length, expected 40 got 34 bytes
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/prem2/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
    at new JsonRpcError (file:///C:/Users/prem2/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
    at file:///C:/Users/prem2/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
 ```

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Invalid address length, expected 40 got 34 bytes
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/prem2/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
>     at new JsonRpcError (file:///C:/Users/prem2/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
>     at file:///C:/Users/prem2/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
> ```

@CodePrem  Please recheck your address and make sure it's the right one.
