### ISSUE TITLE
How to redirect from a site to another site's blog post

### ISSUE THREAD

**Issue by CodePrem** [mintme-com/old-wallet#230]
I want to know "How to redirect from a site to another site's blog post (any random post).
PLEASE ANSWER, IF ANYONE CAN HELP ME!

**Comment by danielwebimp** [comment]
@CodePrem  Hi, your question is not related to MintMe wallet, please try to find it in google you may find more quickly an answer there.

> I want to know "How to redirect from a site to another site's blog post (any random post).
> PLEASE ANSWER, IF ANYONE CAN HELP ME!
